const PDFDocument = require('pdfkit');

/**
 * Build a structured legal PDF report and pipe it into a writable stream (or res).
 *
 * Usage:
 *   const doc = buildLegalReport(data);
 *   doc.pipe(res);   // stream directly to HTTP response
 *   doc.end();
 *
 * data shape:
 * {
 *   complaint: { anonymousToken, category, description, location, createdAt, statusHistory },
 *   evidence:  [{ fileName, sha256Hash, ipfsCid, blockchainTx, uploadedAt }],
 *   laws:      ['Section 354 IPC', 'IT Act 66C'],   // from legal guide
 * }
 */
function buildLegalReport(data) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const { complaint, evidence, laws } = data;

  // ── Header ──────────────────────────────────────────────────────────────────
  doc.fontSize(20).font('Helvetica-Bold').text('SURAKSHA', { align: 'center' });
  doc.fontSize(12).font('Helvetica').text('Unified Safety & Trust Platform', { align: 'center' });
  doc.fontSize(10).fillColor('grey').text('This is a digitally-generated legal report. Evidence hashes are blockchain-verified.', { align: 'center' });
  doc.moveDown();
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown();

  // ── Complaint Details ────────────────────────────────────────────────────────
  doc.fontSize(14).fillColor('black').font('Helvetica-Bold').text('1. Complaint Details');
  doc.moveDown(0.5);
  field(doc, 'Report Token',     complaint.anonymousToken || '—');
  field(doc, 'Category',         complaint.category || '—');
  field(doc, 'Location',         complaint.location || 'Not specified');
  field(doc, 'Filed On',         formatDate(complaint.createdAt));
  field(doc, 'Current Status',   latestStatus(complaint.statusHistory));
  doc.moveDown(0.5);
  doc.fontSize(11).font('Helvetica-Bold').text('Description:');
  doc.fontSize(11).font('Helvetica').text(complaint.description || '—', { indent: 10 });
  doc.moveDown();

  // ── Status History ───────────────────────────────────────────────────────────
  doc.fontSize(14).font('Helvetica-Bold').text('2. Status History');
  doc.moveDown(0.5);
  if (complaint.statusHistory && complaint.statusHistory.length > 0) {
    complaint.statusHistory.forEach((h, i) => {
      doc.fontSize(10).font('Helvetica')
        .text(`${i + 1}. [${formatDate(h.updatedAt)}]  ${h.status.toUpperCase()}${h.note ? ' — ' + h.note : ''}`);
    });
  } else {
    doc.fontSize(10).font('Helvetica').text('No status history available.');
  }
  doc.moveDown();

  // ── Evidence ──────────────────────────────────────────────────────────────────
  doc.fontSize(14).font('Helvetica-Bold').text('3. Digital Evidence');
  doc.moveDown(0.5);
  if (evidence && evidence.length > 0) {
    evidence.forEach((ev, i) => {
      doc.fontSize(11).font('Helvetica-Bold').text(`Evidence ${i + 1}: ${ev.fileName}`);
      field(doc, 'Uploaded On',    formatDate(ev.uploadedAt));
      field(doc, 'SHA-256 Hash',   ev.sha256Hash || '—');
      field(doc, 'IPFS CID',       ev.ipfsCid    || 'Not uploaded to IPFS');
      field(doc, 'Blockchain Tx',  ev.blockchainTx || 'Not timestamped on-chain');
      doc.moveDown(0.5);
    });
  } else {
    doc.fontSize(10).font('Helvetica').text('No evidence attached to this complaint.');
  }
  doc.moveDown();

  // ── Applicable Laws ───────────────────────────────────────────────────────────
  doc.fontSize(14).font('Helvetica-Bold').text('4. Applicable Laws & Rights');
  doc.moveDown(0.5);
  if (laws && laws.length > 0) {
    laws.forEach(law => {
      doc.fontSize(10).font('Helvetica').text(`• ${law}`);
    });
  } else {
    doc.fontSize(10).font('Helvetica').text('No laws specified.');
  }
  doc.moveDown();

  // ── Declaration ───────────────────────────────────────────────────────────────
  doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);
  doc.fontSize(9).fillColor('grey').font('Helvetica')
    .text(
      'This report was auto-generated by Suraksha. All evidence SHA-256 hashes were computed ' +
      'client-side before upload and independently verified server-side. IPFS CIDs are permanent ' +
      'and tamper-evident. Blockchain transaction hashes confirm on-chain timestamping via Polygon network.',
      { align: 'justify' }
    );

  doc.fontSize(9).text(`Generated: ${new Date().toUTCString()}`, { align: 'right' });

  return doc;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function field(doc, label, value) {
  doc.fontSize(10)
    .font('Helvetica-Bold').text(`${label}: `, { continued: true })
    .font('Helvetica').text(value);
}

function formatDate(d) {
  if (!d) return '—';
  return new Date(d).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
}

function latestStatus(history) {
  if (!history || history.length === 0) return 'submitted';
  return history[history.length - 1].status;
}

module.exports = { buildLegalReport };